<?php


class FrontTargetWebModuleFrontController extends ModuleFrontController
{

    /**
     * @see FrontController::initContent()
     */

    public function initContent()
    {
        parent::initContent(); // TODO: Change the autogenerated stub

        $this->setTemplate('test.tpl');
    }


}