<?php

if (!defined('_PS_VERSION_')) {
    exit;
}


class ExerciceNM extends Module
{

    public function __construct($name = null, Context $context = null)
    {
        $this->name = 'exercice';
        $this->tab='font_office_features';
        $this->version='1.0';
        $this->author='MAURIN Nicolas';
        $this->need_instance = 0;
        $this->bootstrap = true;

        parent::__construct();

        $this->displayName = $this->l('Exercice TargetWeb');
        $this->description = $this->l('Page permettant de télécharger une photo avec un texte');

    }

    public function install()
    {
        $this->_clearCache('exerciceNM.tpl');
        return (parent::install()
            && Configuration::updateValue('exerciceNM','')
            && $this->registerHook('displayHome')); // TODO: Change the autogenerated stub
    }

    public function uninstall()
    {
        Configuration::deleteByName('jsvalue');
        if (!parent::uninstall()){
            return false;
        }
        return true;
    }

}